apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: myapp
          # image: non-existent-image:latest # 존재하지 않는 이미지
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi