apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: myapp
        image: polinux/stress
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 100m
            # memory: "100Mi"
            memory: "200Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    
