apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: 11-senario

resources:
  - ../base
  - namespace.yaml
  - ingress.yaml
  # - hpa.yaml
  # - overprovisioning.yaml

patches:
  - path: ui.yaml
