apiVersion: v1
kind: Service
metadata:
  name: ui
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-type: external
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  template:
    spec:
      containers:
        - name: ui
          # 서비스의 가용성을 높이기 위해서 readinessProbe 활용하자!
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 3
          # Graceful shutdown을 위한 설정2
          # lifecycle:
          #   preStop:
          #     exec:
          #       command:
          #         - /bin/sh
          #         - "-c"
          #         - sleep 80
      # Graceful shutdown을 위한 설정1
      # terminationGracePeriodSeconds: 90
