# Dockerfile
FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN pip3 install flask --break-system-packages

COPY . /app
WORKDIR /app

CMD ["python3", "app.py"]