apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-guestbook-ui
spec:
  selector:
    matchLabels:
      app: kustomize-guestbook-ui
  template:
    metadata:
      labels:
        app: kustomize-guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: kustomize-guestbook-ui
        ports:
        - name: http
          containerPort: 80
        envFrom:
        - configMapRef:
            name: guestbook-config
