apiVersion: v1
kind: Namespace
metadata:
  name: 08-senario
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  namespace: 08-senario
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
        - name: my-nginx
          image: nginx
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - "-c"
                  - sleep 15
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: run
                operator: In
                values:
                - my-nginx
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: 08-senario
  labels:
    run: my-nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: my-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: 08-senario
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing              
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/load-balancer-name: part01-nginx-old    # aws loadbalancer controller가 해당 annotation을 읽고, 로드밸런서 이름을 설정함 
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-nginx
                port:
                  name: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: 08-senario
spec:
  minAvailable: 2
  selector:
    matchLabels:
      run: my-nginx

