apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: guestbook-ui-svc.yaml
- path: guestbook-ui-deployment.yaml

helmGlobals:
  chartHome: ../../

helmCharts:
- name: "02-helm"
  releaseName: kustomize-helm-guestbook
  valuesFile: ./values.yaml