FROM node:18-alpine AS base

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev


FROM node:18-alpine AS deploy

ARG VERSION
ENV VERSION ${VERSION}

WORKDIR /app

COPY --from=base /app/node_modules ./node_modules

COPY . .

CMD ["npm", "start"]