FROM ubuntu:latest

COPY . .

# install nodejs
RUN apt-get -qq update
RUN apt-get -qq upgrade --yes 
RUN apt-get -qq install curl --yes
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get -qq install nodejs --yes

ARG VERSION
ENV VERSION ${VERSION}

WORKDIR /app

COPY package*.json ./

RUN npm install

CMD ["npm", "start"]
