apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: guestbook-ui
spec:
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: kustomize02-aws-cluster-secret-store
  dataFrom:
    - extract:
        key: part02/senario06
