apiVersion: v1
kind: Namespace
metadata:
  name: 09-senario
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: 09-senario
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: hulkong/fastcampus-devops-practice-examples-100:09-senario-01
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health-check
            port: 3000
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 1
          successThreshold: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: 09-senario
spec:
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
          name: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: 09-senario
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb
