apiVersion: v1
kind: Namespace
metadata:
  name: 09-senario
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: 09-senario
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: hulkong/fastcampus-devops-practice-examples-100:09-senario-02
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /cpu
            port: 3000
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 1
          successThreshold: 1