apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
# Base64 encoded values
data:
  AVP_TYPE: YXdzc2VjcmV0c21hbmFnZXI=
  AWS_REGION: dXMtZWFzdC0y
