apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: my-namespace
spec:
  hard:
    requests.memory: 800Mi
    limits.memory: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: my-namespace
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: myapp
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.7
          resources:
            limits:
              cpu: "500m"
              # memory: 2Gi
              memory: 200Mi
            requests:
              cpu: "500m"
              # memory: 1Gi
              memory: 200Mi
