name: 느린 예시 CI(도커라이징이 최적화 되었지만...)

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Image Version'
        required: true
        default: 'latest'

defaults:
  run:
    working-directory: '02-강의준비/08-실무미션'
        
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Run Test
        run: npm test


      # 도커 빌드 및 푸시를 진행합니다. 다만, 플랫폼을 시퀀셜하게 빌드하므로 빌드속도가 느립니다.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '02-강의준비/08-실무미션'
          file: '02-강의준비/08-실무미션/Dockerfile.optimize'
          platforms: linux/amd64,linux/arm/v7
          build-args: |
            VERSION=${{ github.event.inputs.imageVersion }}
          push: true
          tags: hulkong/fastcampus-devops-practice-examples-100:part02-08-senario-${{ github.event.inputs.imageVersion }}