apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "{{ include "mongodb.name" . }}"
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "mongodb.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongodb.name" . }}
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: {{ .Values.service.port }}
          name: mongodb
